### ISSUE TITLE
Docker Swarm does not work with socket

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/mu-swarm-logger-service#1]
Hi! 

I am not really sure about the purpose of this logger service as there is no description in README file. Please, add description (and how it will be used in BDE project) and related components, which depends on the logger. 

FYI it will not work with the setup we have in BDE project at the moment, because you need to read events on port 4000 of swarm-manager container (see installation guide in README repo) By simply connecting to the socket the half of events will be ignored. 

For TCP connection you might check the repo from which you copied the ontology parts. 

Also, if you use the ontology in the code, it has to be documented. As we do not publish ontology publicly, it should be added directly to the repository, which uses the ontology (see owl files in the root of docker-event2rdf).

The better solution might be to have a library which converts events to RDF and use it as an external dependency (simply installing with pip). Otherwise, we possibly end up maintaining two similar repos with duplicate functionality.

**Comment by madnificent** [comment]
Hi Ivan.  Thanks for your spot-on comments.  It was indeed the idea to keep only one.  This is an informative comment, not a solution to the issues you mention.

We want information from the daemon for three cases: network logging, log monitoring & the init_daemon.  It makes sense to integrate these three requirements into one microservice that exports all interesting/necessary information to the triplestore.  By exporting from one service, we make consumption of this ever growing set of information easier.

The mu-swarm-logger-service monitors the daemon (but ideally the swarm master), and writes the logs to the triplestore or to a file.  Other services can pick up this log and render it in the frontend.  This is what we want for the SwarmUI.  The mu-swarm-logger-service is written asynchronously as there are multiple logs to monitor.  This seems to make it harder to port the logger to docker-event2rdf rather than the other way around.  Feel free to indicate otherwise.  We intend to take the happy path forward.

If there is no reference to https://github.com/earthquakesan/docker-event2rdf in the commits, then this must be an oversight.  We should add the reference in the docs or the commits, regardless of which one(s) we keep alive.
